///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Instagram.Modules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Follow recording.
    /// </summary>
    [TestModule("1c450e28-e839-43d6-ab98-35b4b3acf948", ModuleType.Recording, 1)]
    public partial class Follow : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Instagram.InstagramRepository repository.
        /// </summary>
        public static global::Instagram.InstagramRepository repo = global::Instagram.InstagramRepository.Instance;

        static Follow instance = new Follow();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Follow()
        {
            Suchen = "leandrolevin";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Follow Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Suchen.
        /// </summary>
        [TestVariable("2ec227ed-dbe0-4e8d-9af8-1a70eca8df7d")]
        public string Suchen
        {
            get { return repo.Suchen; }
            set { repo.Suchen = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Follow.Search' at Center.", repo.ApplicationUnderTest.Follow.SearchInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Follow.Search.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Suchen' with focus on 'ApplicationUnderTest.Follow.Text'.", repo.ApplicationUnderTest.Follow.TextInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Follow.Text.PressKeys(Suchen);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.Follow.Leandrolevin'", repo.ApplicationUnderTest.Follow.LeandrolevinInfo, new ActionTimeout(5000), new RecordItemIndex(2));
            repo.ApplicationUnderTest.Follow.LeandrolevinInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Follow.Leandrolevin' at Center.", repo.ApplicationUnderTest.Follow.LeandrolevinInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Follow.Leandrolevin.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.Follow.Username'", repo.ApplicationUnderTest.Follow.UsernameInfo, new ActionTimeout(5000), new RecordItemIndex(4));
            repo.ApplicationUnderTest.Follow.UsernameInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Follow.Folgen' at Center.", repo.ApplicationUnderTest.Follow.FolgenInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Follow.Folgen.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
