///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Instagram
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the InstagramRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("deaff906-203b-4c21-a8dd-a3ae7976901d")]
    public partial class InstagramRepository : RepoGenBaseFolder
    {
        static InstagramRepository instance = new InstagramRepository();
        InstagramRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the InstagramRepository element repository.
        /// </summary>
        [RepositoryFolder("deaff906-203b-4c21-a8dd-a3ae7976901d")]
        public static InstagramRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public InstagramRepository() 
            : base("InstagramRepository", "/", null, 0, false, "deaff906-203b-4c21-a8dd-a3ae7976901d", ".\\RepositoryImages\\InstagramRepositorydeaff906.rximgres")
        {
            _applicationundertest = new InstagramRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

        string _Suchen = "leandrolevin";

        /// <summary>
        /// Gets or sets the value of variable Suchen.
        /// </summary>
        [TestVariable("5626d3d6-e8b7-42c4-8e59-41b745b6fa9c")]
        public string Suchen
        {
            get { return _Suchen; }
            set { _Suchen = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("deaff906-203b-4c21-a8dd-a3ae7976901d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("6b75073c-635a-4c76-b035-7d8552f80afb")]
        public virtual InstagramRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class InstagramRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("6b75073c-635a-4c76-b035-7d8552f80afb")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            InstagramRepositoryFolders.RegistrationFolder _registration;
            InstagramRepositoryFolders.LoginFolder _login;
            InstagramRepositoryFolders.FollowFolder _follow;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.instagram.com']", parentFolder, 30000, null, false, "6b75073c-635a-4c76-b035-7d8552f80afb", "")
            {
                _registration = new InstagramRepositoryFolders.RegistrationFolder(this);
                _login = new InstagramRepositoryFolders.LoginFolder(this);
                _follow = new InstagramRepositoryFolders.FollowFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6b75073c-635a-4c76-b035-7d8552f80afb")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6b75073c-635a-4c76-b035-7d8552f80afb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Registration folder.
            /// </summary>
            [RepositoryFolder("5a8281df-a68d-49be-887b-49af6d14416c")]
            public virtual InstagramRepositoryFolders.RegistrationFolder Registration
            {
                get { return _registration; }
            }

            /// <summary>
            /// The Login folder.
            /// </summary>
            [RepositoryFolder("9fcbdfb3-e810-4b60-8d3f-0a735a9e54a7")]
            public virtual InstagramRepositoryFolders.LoginFolder Login
            {
                get { return _login; }
            }

            /// <summary>
            /// The Follow folder.
            /// </summary>
            [RepositoryFolder("af7a380a-e1dc-4647-9e00-75f9add58fb0")]
            public virtual InstagramRepositoryFolders.FollowFolder Follow
            {
                get { return _follow; }
            }
        }

        /// <summary>
        /// The RegistrationFolder folder.
        /// </summary>
        [RepositoryFolder("5a8281df-a68d-49be-887b-49af6d14416c")]
        public partial class RegistrationFolder : RepoGenBaseFolder
        {
            InstagramRepositoryFolders.Page_1Folder _page_1;
            InstagramRepositoryFolders.Page_2Folder _page_2;
            InstagramRepositoryFolders.Page_3Folder _page_3;

            /// <summary>
            /// Creates a new Registration  folder.
            /// </summary>
            public RegistrationFolder(RepoGenBaseFolder parentFolder) :
                    base("Registration", "", parentFolder, 0, null, false, "5a8281df-a68d-49be-887b-49af6d14416c", "")
            {
                _page_1 = new InstagramRepositoryFolders.Page_1Folder(this);
                _page_2 = new InstagramRepositoryFolders.Page_2Folder(this);
                _page_3 = new InstagramRepositoryFolders.Page_3Folder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5a8281df-a68d-49be-887b-49af6d14416c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Page_1 folder.
            /// </summary>
            [RepositoryFolder("e9583579-eede-4f23-8696-46d2d3af719e")]
            public virtual InstagramRepositoryFolders.Page_1Folder Page_1
            {
                get { return _page_1; }
            }

            /// <summary>
            /// The Page_2 folder.
            /// </summary>
            [RepositoryFolder("e5744c74-b947-4653-8418-d395ec806ac1")]
            public virtual InstagramRepositoryFolders.Page_2Folder Page_2
            {
                get { return _page_2; }
            }

            /// <summary>
            /// The Page_3 folder.
            /// </summary>
            [RepositoryFolder("db0473d8-bddd-412e-9699-81ad6bb0ecf8")]
            public virtual InstagramRepositoryFolders.Page_3Folder Page_3
            {
                get { return _page_3; }
            }
        }

        /// <summary>
        /// The Page_1Folder folder.
        /// </summary>
        [RepositoryFolder("e9583579-eede-4f23-8696-46d2d3af719e")]
        public partial class Page_1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _registrierenInfo;
            RepoItemInfo _weiterInfo;
            RepoItemInfo _emailorphoneInfo;
            RepoItemInfo _fullnameInfo;

            /// <summary>
            /// Creates a new Page_1  folder.
            /// </summary>
            public Page_1Folder(RepoGenBaseFolder parentFolder) :
                    base("Page_1", "", parentFolder, 0, null, false, "e9583579-eede-4f23-8696-46d2d3af719e", "")
            {
                _registrierenInfo = new RepoItemInfo(this, "Registrieren", ".//?/?/?/?/?//?/?/?/span[@innertext='Registrieren']", 30000, null, "70f3b3c4-ce19-49ef-a3b2-fd5379786bf7");
                _weiterInfo = new RepoItemInfo(this, "Weiter", ".//?/?//?//?/?/?/?/button[@innertext='Weiter']", 30000, null, "12f17e8e-6dab-448c-afea-d988f3ee4b61");
                _emailorphoneInfo = new RepoItemInfo(this, "EmailOrPhone", ".//?/?/?/?/?/?//?/?//input[@name='emailOrPhone']", 30000, null, "753983eb-b5fd-4ba9-8176-ffb21fbc807e");
                _fullnameInfo = new RepoItemInfo(this, "FullName", ".//?/?/?/?/?/?//?/?//input[@name='fullName']", 30000, null, "e6ef1a8f-073f-49d0-a069-3d17fc0c7174");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e9583579-eede-4f23-8696-46d2d3af719e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Registrieren item.
            /// </summary>
            [RepositoryItem("70f3b3c4-ce19-49ef-a3b2-fd5379786bf7")]
            public virtual Ranorex.SpanTag Registrieren
            {
                get
                {
                    return _registrierenInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Registrieren item info.
            /// </summary>
            [RepositoryItemInfo("70f3b3c4-ce19-49ef-a3b2-fd5379786bf7")]
            public virtual RepoItemInfo RegistrierenInfo
            {
                get
                {
                    return _registrierenInfo;
                }
            }

            /// <summary>
            /// The Weiter item.
            /// </summary>
            [RepositoryItem("12f17e8e-6dab-448c-afea-d988f3ee4b61")]
            public virtual Ranorex.ButtonTag Weiter
            {
                get
                {
                    return _weiterInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Weiter item info.
            /// </summary>
            [RepositoryItemInfo("12f17e8e-6dab-448c-afea-d988f3ee4b61")]
            public virtual RepoItemInfo WeiterInfo
            {
                get
                {
                    return _weiterInfo;
                }
            }

            /// <summary>
            /// The EmailOrPhone item.
            /// </summary>
            [RepositoryItem("753983eb-b5fd-4ba9-8176-ffb21fbc807e")]
            public virtual Ranorex.InputTag EmailOrPhone
            {
                get
                {
                    return _emailorphoneInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EmailOrPhone item info.
            /// </summary>
            [RepositoryItemInfo("753983eb-b5fd-4ba9-8176-ffb21fbc807e")]
            public virtual RepoItemInfo EmailOrPhoneInfo
            {
                get
                {
                    return _emailorphoneInfo;
                }
            }

            /// <summary>
            /// The FullName item.
            /// </summary>
            [RepositoryItem("e6ef1a8f-073f-49d0-a069-3d17fc0c7174")]
            public virtual Ranorex.InputTag FullName
            {
                get
                {
                    return _fullnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FullName item info.
            /// </summary>
            [RepositoryItemInfo("e6ef1a8f-073f-49d0-a069-3d17fc0c7174")]
            public virtual RepoItemInfo FullNameInfo
            {
                get
                {
                    return _fullnameInfo;
                }
            }
        }

        /// <summary>
        /// The Page_2Folder folder.
        /// </summary>
        [RepositoryFolder("e5744c74-b947-4653-8418-d395ec806ac1")]
        public partial class Page_2Folder : RepoGenBaseFolder
        {
            RepoItemInfo _jahrInfo;
            RepoItemInfo _monatInfo;
            RepoItemInfo _tagInfo;

            /// <summary>
            /// Creates a new Page_2  folder.
            /// </summary>
            public Page_2Folder(RepoGenBaseFolder parentFolder) :
                    base("Page_2", "", parentFolder, 0, null, false, "e5744c74-b947-4653-8418-d395ec806ac1", "")
            {
                _jahrInfo = new RepoItemInfo(this, "Jahr", ".//?/?/?/?/?/?/?/?/?/?//select[@title='Jahr:']", 30000, null, "928c3ad2-ff5a-42de-8c09-c7519d7a90ed");
                _monatInfo = new RepoItemInfo(this, "Monat", ".//?/?/?/?/?/?/?/?/?/?//select[@title='Monat:']", 30000, null, "565ae0d7-bc12-4e03-b0ba-c6a197c94b20");
                _tagInfo = new RepoItemInfo(this, "Tag", ".//?/?/?/?/?/?/?/?/?/?//select[@title='Tag:']", 30000, null, "2ee19b9b-c826-4aef-9ac5-4ff946bff023");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e5744c74-b947-4653-8418-d395ec806ac1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Jahr item.
            /// </summary>
            [RepositoryItem("928c3ad2-ff5a-42de-8c09-c7519d7a90ed")]
            public virtual Ranorex.SelectTag Jahr
            {
                get
                {
                    return _jahrInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Jahr item info.
            /// </summary>
            [RepositoryItemInfo("928c3ad2-ff5a-42de-8c09-c7519d7a90ed")]
            public virtual RepoItemInfo JahrInfo
            {
                get
                {
                    return _jahrInfo;
                }
            }

            /// <summary>
            /// The Monat item.
            /// </summary>
            [RepositoryItem("565ae0d7-bc12-4e03-b0ba-c6a197c94b20")]
            public virtual Ranorex.SelectTag Monat
            {
                get
                {
                    return _monatInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Monat item info.
            /// </summary>
            [RepositoryItemInfo("565ae0d7-bc12-4e03-b0ba-c6a197c94b20")]
            public virtual RepoItemInfo MonatInfo
            {
                get
                {
                    return _monatInfo;
                }
            }

            /// <summary>
            /// The Tag item.
            /// </summary>
            [RepositoryItem("2ee19b9b-c826-4aef-9ac5-4ff946bff023")]
            public virtual Ranorex.SelectTag Tag
            {
                get
                {
                    return _tagInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Tag item info.
            /// </summary>
            [RepositoryItemInfo("2ee19b9b-c826-4aef-9ac5-4ff946bff023")]
            public virtual RepoItemInfo TagInfo
            {
                get
                {
                    return _tagInfo;
                }
            }
        }

        /// <summary>
        /// The Page_3Folder folder.
        /// </summary>
        [RepositoryFolder("db0473d8-bddd-412e-9699-81ad6bb0ecf8")]
        public partial class Page_3Folder : RepoGenBaseFolder
        {
            RepoItemInfo _emailconfirmationcodeInfo;

            /// <summary>
            /// Creates a new Page_3  folder.
            /// </summary>
            public Page_3Folder(RepoGenBaseFolder parentFolder) :
                    base("Page_3", "", parentFolder, 0, null, false, "db0473d8-bddd-412e-9699-81ad6bb0ecf8", "")
            {
                _emailconfirmationcodeInfo = new RepoItemInfo(this, "EmailConfirmationCode", ".//?/?//?/?/?/?/?/?/?/?/input[@name='email_confirmation_code']", 30000, null, "a08b32d5-5569-44e5-9afc-cdb64b33c3bd");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("db0473d8-bddd-412e-9699-81ad6bb0ecf8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EmailConfirmationCode item.
            /// </summary>
            [RepositoryItem("a08b32d5-5569-44e5-9afc-cdb64b33c3bd")]
            public virtual Ranorex.InputTag EmailConfirmationCode
            {
                get
                {
                    return _emailconfirmationcodeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EmailConfirmationCode item info.
            /// </summary>
            [RepositoryItemInfo("a08b32d5-5569-44e5-9afc-cdb64b33c3bd")]
            public virtual RepoItemInfo EmailConfirmationCodeInfo
            {
                get
                {
                    return _emailconfirmationcodeInfo;
                }
            }
        }

        /// <summary>
        /// The LoginFolder folder.
        /// </summary>
        [RepositoryFolder("9fcbdfb3-e810-4b60-8d3f-0a735a9e54a7")]
        public partial class LoginFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _anmeldenInfo;

            /// <summary>
            /// Creates a new Login  folder.
            /// </summary>
            public LoginFolder(RepoGenBaseFolder parentFolder) :
                    base("Login", "", parentFolder, 0, null, false, "9fcbdfb3-e810-4b60-8d3f-0a735a9e54a7", "")
            {
                _usernameInfo = new RepoItemInfo(this, "Username", ".//?/?/?/?/?//?/?//input[@name='username']", 30000, null, "59070ef5-a35d-4287-8571-1a0f0ef18b1a");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//?/?/?/?/?//?/?//input[@name='password']", 30000, null, "d57274a0-5f94-4589-8237-0d0567c0943f");
                _anmeldenInfo = new RepoItemInfo(this, "Anmelden", ".//?/?/?/?/?//?/?/?/?/div[@innertext='Anmelden']", 30000, null, "9c4588bc-d9c1-4760-bb25-7b8a89f1964a");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9fcbdfb3-e810-4b60-8d3f-0a735a9e54a7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("59070ef5-a35d-4287-8571-1a0f0ef18b1a")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("59070ef5-a35d-4287-8571-1a0f0ef18b1a")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("d57274a0-5f94-4589-8237-0d0567c0943f")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("d57274a0-5f94-4589-8237-0d0567c0943f")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Anmelden item.
            /// </summary>
            [RepositoryItem("9c4588bc-d9c1-4760-bb25-7b8a89f1964a")]
            public virtual Ranorex.DivTag Anmelden
            {
                get
                {
                    return _anmeldenInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Anmelden item info.
            /// </summary>
            [RepositoryItemInfo("9c4588bc-d9c1-4760-bb25-7b8a89f1964a")]
            public virtual RepoItemInfo AnmeldenInfo
            {
                get
                {
                    return _anmeldenInfo;
                }
            }
        }

        /// <summary>
        /// The FollowFolder folder.
        /// </summary>
        [RepositoryFolder("af7a380a-e1dc-4647-9e00-75f9add58fb0")]
        public partial class FollowFolder : RepoGenBaseFolder
        {
            RepoItemInfo _searchInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _leandrolevinInfo;
            RepoItemInfo _folgenInfo;
            RepoItemInfo _usernameInfo;

            /// <summary>
            /// Creates a new Follow  folder.
            /// </summary>
            public FollowFolder(RepoGenBaseFolder parentFolder) :
                    base("Follow", "", parentFolder, 0, null, false, "af7a380a-e1dc-4647-9e00-75f9add58fb0", "")
            {
                _searchInfo = new RepoItemInfo(this, "Search", ".//?/?/?/?/?/?/?//span[@innertext='Suchen']", 30000, null, "b87c3692-823a-4fc5-9f00-b8266ad637f3");
                _textInfo = new RepoItemInfo(this, "Text", ".//?/?/?//input[@type='text']", 30000, null, "184468bf-13b3-4731-9ba0-3a6abcd2c61d");
                _leandrolevinInfo = new RepoItemInfo(this, "Leandrolevin", ".//?/?/?/?/?/?/?/?/?/?/?/?//span[@innertext=$Suchen]", 30000, null, "a1b4435a-d3dd-471c-b457-76f142d98088");
                _folgenInfo = new RepoItemInfo(this, "Folgen", ".//?/?//?/?/?/?/button[@innertext='Folgen']", 30000, null, "432d0a85-1b99-4493-82ad-ec35a5fe72db");
                _usernameInfo = new RepoItemInfo(this, "Username", ".//?/?//?/?/?/?/h2[@innertext=$Suchen]", 30000, null, "ef22320d-ff40-4af6-aacd-27342947b90a");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("af7a380a-e1dc-4647-9e00-75f9add58fb0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Search item.
            /// </summary>
            [RepositoryItem("b87c3692-823a-4fc5-9f00-b8266ad637f3")]
            public virtual Ranorex.SpanTag Search
            {
                get
                {
                    return _searchInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Search item info.
            /// </summary>
            [RepositoryItemInfo("b87c3692-823a-4fc5-9f00-b8266ad637f3")]
            public virtual RepoItemInfo SearchInfo
            {
                get
                {
                    return _searchInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("184468bf-13b3-4731-9ba0-3a6abcd2c61d")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("184468bf-13b3-4731-9ba0-3a6abcd2c61d")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Leandrolevin item.
            /// </summary>
            [RepositoryItem("a1b4435a-d3dd-471c-b457-76f142d98088")]
            public virtual Ranorex.SpanTag Leandrolevin
            {
                get
                {
                    return _leandrolevinInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Leandrolevin item info.
            /// </summary>
            [RepositoryItemInfo("a1b4435a-d3dd-471c-b457-76f142d98088")]
            public virtual RepoItemInfo LeandrolevinInfo
            {
                get
                {
                    return _leandrolevinInfo;
                }
            }

            /// <summary>
            /// The Folgen item.
            /// </summary>
            [RepositoryItem("432d0a85-1b99-4493-82ad-ec35a5fe72db")]
            public virtual Ranorex.ButtonTag Folgen
            {
                get
                {
                    return _folgenInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Folgen item info.
            /// </summary>
            [RepositoryItemInfo("432d0a85-1b99-4493-82ad-ec35a5fe72db")]
            public virtual RepoItemInfo FolgenInfo
            {
                get
                {
                    return _folgenInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("ef22320d-ff40-4af6-aacd-27342947b90a")]
            public virtual Ranorex.H2Tag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("ef22320d-ff40-4af6-aacd-27342947b90a")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
